spring.application.name=bookly

# ?? Database ??
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bookly_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA ??
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Logging ??
logging.level.org.springframework.security=DEBUG

# ?? JWT ??
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# ?? Swagger ??
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.server-url=https://bookly-rest-production.up.railway.app
# ?? Server ??
server.port=8080